global using FluentValidation;
global using Innova.Domain.Interfaces;
global using Mapster;
global using System.Collections.Generic;
global using System.Reflection;
global using Innova.Domain.Specifications;
global using Innova.Domain.Entities;
global using Innova.Application.DTOs;
global using Innova.Application.Services.Interfaces;
