global using System.Collections.Generic;
global using System.Threading.Tasks;
global using Microsoft.AspNetCore.Mvc;
global using Innova.Application.DTOs;
global using Innova.Application.Services.Interfaces;
global using Innova.Application.Services.Implementations;
global using System.Net;
global using System.Text.Json;
global using Serilog;
